{{- if .Values.autoscaling }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.service.app }}
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ .Values.service.app }}
    apiVersion: apps/v1
  minReplicas: {{ .Values.autoscaling.minReplicas | default 2 }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas | default 8 }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.averageUtilization | default 50 }}

{{- end }}
