{{- range $cron := $.Values.cron }}

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $.Values.service.app }}-cron-{{ $cron.name }}
  annotations:
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  schedule: "{{ $cron.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          imagePullSecrets:
            - name: {{ $.Values.image.imagePullSecrets }}
          terminationGracePeriodSeconds: 30
          containers:
            - name: {{ $.Values.service.app }}-{{ $cron.name }}
              image: "{{ $.Values.image.registryfullpath }}/fpm:{{ $.Values.image.tag }}"
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  cpu: 500m
                requests:
                  cpu: 10m
              command: ["/bin/bash", "-c"]
              args: ["{{ $cron.args }}"]
              env:
                - name: DEPLOYMENT_DATE
                  value: {{ now | quote }}
                - name: TZ
                  value: America/New_York
    {{- include "fpm.secrets" (list $ . ) | indent 16 }}
    {{- range $secret := $cron.secrets }}
                - name: {{ $secret.name }}
                  valueFrom:
                    secretKeyRef:
                      name: {{ $.Values.onepassitem }}
                      key: {{ $secret.name }}
    {{- end }}
              volumeMounts:
                - name: env
                  mountPath: /app/.env
                  subPath: env
    {{- range $volume := $cron.volumeMounts }}
                - name: {{ $volume.name }}
                  readOnly: true
                  mountPath: {{ $volume.mountPath }}
                  subPath: {{ $volume.subPath }}
    {{- end }}
    
          volumes:
            - name: env
              configMap:
                name: {{ $.Values.service.app }}
    {{- range $volume := $cron.volumeMounts }}
            - name: {{ $volume.name }}
              secret:
                secretName: {{ $.Values.onepassitem }}
                defaultMode: 432
    {{- end }}
    
    
    
    
    
{{- end }}
    
