{{- if .Values.phptests.enabled }}
{{- if .Values.functionaltest.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-functional"
  annotations:
    "helm.sh/hook": "test-success"
spec:
  containers:
    - name: functional
      image: {{ include "fpm.image" . }}
      imagePullPolicy: {{ .Values.image.pullPolicy | IfNotPresent }}
      resources:
        limits:
          cpu: 500m
        requests:
          cpu: 10m
      command: ["/bin/bash", "-c"]
      args: ["cd /app/; /bin/bash ./functional.sh"]
      env:
      - name: test_url
        value: {{ .Values.service.app }}:8080
      - name: TEST_URL
        value: {{ .Values.service.app }}:8080
      volumeMounts:
{{- include "fpm.volumeMounts" (list $ . ) | indent 8 }}
  volumes:
{{- include "fpm.volumes" (list $ . ) | indent 4 }}
  restartPolicy: Never
  nodeSelector:
    {{ .Values.nodeSelector.name }}: {{ .Values.nodeSelector.labels }}
  imagePullSecrets:
    - name: {{ .Values.image.imagePullSecrets }}

{{- end -}}
{{- end -}}
