{{- if .Values.onepass.enabled }}
{{- range $onepass := $.Values.onepassitems }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ $onepass }}
spec:
  itemPath: "vaults/{{ $.Values.global.env }}/items/{{ $onepass }}"


{{- end -}}
{{- end -}}
