{{- if .Values.onepass.enabled }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ $.Values.onepassitem }}
spec:
  itemPath: "vaults/{{ $.Values.global.env }}/items/{{ $.Values.onepassitem }}"


{{- end -}}
