{{- if .Values.selenium.enabled }}

apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-selenium"
  annotations:
    "helm.sh/hook": "test-success"
spec:
  containers:
    - name: selenium
      image: selenium/standalone-chrome:latest
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      resources:
        limits:
          cpu: 500m
        requests:
          cpu: 10m
      command: ["/bin/bash", "-c"]
      args: ["cd /app/; /bin/bash ./functional.sh"]
      env:
      - name: test_url
        value: {{ .Values.service.app }}:8080
      - SE_NODE_MAX_SESSIONS: 10
      - SE_NODE_SESSION_TIMEOUT: 100
      - SE_NODE_OVERRIDE_MAX_SESSIONS: true
      volumeMounts:
  restartPolicy: Never
  nodeSelector:
    {{ .Values.nodeSelector.name }}: {{ .Values.nodeSelector.labels }}

{{- end -}}
