kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.service.app }}
spec:
  selector:
    app: {{ .Values.service.app }}
  ports:
{{- range $port := $.Values.ports }}
  - name: {{ $port.name }}
    protocol: TCP
    port: {{ $port.portNumber }}
{{- end }}
  - name: memcached
    protocol: TCP
    port: 11211

{{- if .Values.selenium.enabled }}
  - name: selenium
    protocol: TCP
    port: 4444
  - name: selenium2
    protocol: TCP
    port: 7900
{{- end }}

