{{- if .Values.phptests.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-functional"
  annotations:
    "helm.sh/hook": "test-success"
spec:
  containers:
    - name: functional
      image: {{ include "fpm.image" . }}
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      resources:
        limits:
          cpu: 500m
        requests:
          cpu: 10m
      command: ["/bin/bash", "-c"]
      args: ["cd /app/; /bin/bash ./functional.sh"]
      env:
      - name: test_url
        value: {{ .Values.service.app }}:8080
      volumeMounts:
        - name: env
          mountPath: /app/.env
          subPath: env
  volumes:
    - name: env
      configMap:
        name: {{ .Values.service.app }}-{{ .Values.global.env }}
  restartPolicy: Never
  nodeSelector:
    {{ .Values.nodeSelector.name }}: {{ .Values.nodeSelector.labels }}
  imagePullSecrets:
    - name: {{ .Values.image.imagePullSecrets }}

{{- end -}}
