apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-unit"
  labels:
    app: {{ .Values.service.app }}
  annotations:
    "helm.sh/hook": "test"
    "helm.sh/hook-weight": "-1"
spec:
  containers:
    - name: unit
      image: {{ include "fpm.image" . }}
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      resources:
        limits:
          cpu: 500m
        requests:
          cpu: 10m
      command: ["bash", "-c"]
      args: ["cd /app/; /bin/bash ./unit.sh --coverage-text --no-colors"]
      volumeMounts:
        - name: env
          mountPath: /app/.env
          subPath: env
  volumes:
    - name: env
      configMap:
        name: {{ .Values.service.app }}-{{ .Values.global.env }}
  restartPolicy: Never
  nodeSelector:
     {{ .Values.nodeSelector.name }}: {{ .Values.nodeSelector.labels }}
  imagePullSecrets:
    - name: {{ .Values.image.imagePullSecrets }}
