{{- if .Values.phptests.enabled }}
{{- if .Values.unittest.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-unit"
  annotations:
    "helm.sh/hook": "test-success"
spec:
  containers:

    - name: unit
      image: {{ include "fpm.image" . }}
      imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}

      resources:
        limits:
          cpu: 500m
          memory: {{ .Values.unittest.memorylimit | default "256Mi" }}
        requests:
          cpu: 10m

      command: ["/bin/bash", "-c"]
      args: ["cd /app/; /bin/bash ./unit.sh --coverage-text --no-colors"]

      env:
      - name: test_url
        value: {{ .Values.service.app }}:8080

      volumeMounts:
{{- include "fpm.volumeMounts" (list $ . ) | indent 8 }}

  volumes:
{{- include "fpm.volumes" (list $ . ) | indent 4 }}

  restartPolicy: Never
  nodeSelector:
    {{ .Values.nodeSelector.name }}: {{ .Values.nodeSelector.labels }}
  imagePullSecrets:
    - name: {{ .Values.image.imagePullSecrets }}

{{- end -}}
{{- end -}}
