
{{- range $worker := $.Values.workers }}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ $.Values.service.app }}-{{ $worker.name }}
  name: {{ $.Values.service.app }}-{{ $worker.name }}
spec:
  replicas: {{ $worker.replicaCount }}
  selector:
    matchLabels:
      app: {{ $.Values.service.app }}-{{ $worker.name }}
  template:
    metadata:
      labels:
        app: {{ $.Values.service.app }}-{{ $worker.name }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: {{ $.Values.service.app }}-{{ $worker.name }}
          image: "{{ $.Values.image.registryfullpath }}/fpm:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          resources:
            limits:
              cpu: 500m
              memory: {{ $worker.memorylimit | default "256Mi" }}
            requests:
              cpu: 10m
              memory: 32Mi
          command: ["/bin/bash", "-c"]
          args: ["{{ $worker.args }}"]
          env:
{{- include "fpm.secrets" (list $ . ) | indent 12 }}
            - name: DEPLOYMENT_DATE
              value: {{ now | quote }}
            - name: TZ
              value: America/New_York
          volumeMounts:
{{- include "fpm.volumeMounts" (list $ . ) | indent 12 }}

      volumes:
{{- include "fpm.volumes" (list $ . ) | indent 8 }}
      restartPolicy: Always
      nodeSelector:
        {{ $.Values.nodeSelector.name }}: workers
      imagePullSecrets:
        - name: {{ $.Values.image.imagePullSecrets }}
      terminationGracePeriodSeconds: 30

{{- end }}

