{{- range $worker := $.Values.workers }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ $.Values.service.app }}-worker-{{ $worker.name }}
  name: {{ $.Values.service.app }}-worker-{{ $worker.name }}
  annotations:
{{- if $.Values.onepass.enabled }}
    operator.1password.io/auto-restart: "true"
    operator.1password.io/item-path: "vaults/{{ $.Values.global.onepassvault }}/items/{{ $.Values.onepassitem }}"
    operator.1password.io/item-name: "{{ $.Values.onepassitem }}"
{{- end }}
spec:
  replicas: {{ $worker.replicaCount }}
  selector:
    matchLabels:
      app: {{ $.Values.service.app }}-worker-{{ $worker.name }}
  template:
    metadata:
      labels:
        app: {{ $.Values.service.app }}-worker-{{ $worker.name }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: {{ $.Values.service.app }}-worker-{{ $worker.name }}
          image: "{{ $.Values.image.registryfullpath }}/fpm:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy | IfNotPresent }}
          resources:
            limits:
              cpu: 500m
              memory: {{ $worker.memorylimit | default "256Mi" }}
            requests:
              cpu: 10m
              memory: 16Mi
          command: ["/bin/bash", "-c"]
          args: ["{{ $worker.args }}"]
          env:
{{- include "fpm.secrets" (list $ . ) | indent 12 }}
{{- range $secret := $worker.secrets }}
            - name: {{ $secret.name }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.onepassitem }}
                  key: {{ $secret.name }}
{{- end }}
            - name: DEPLOYMENT_DATE
              value: {{ now | quote }}
            - name: TZ
              value: America/New_York
          volumeMounts:
            - name: env
              mountPath: /app/.env
              subPath: env
{{- range $volume := $worker.volumeMounts }}
            - name: {{ $volume.name }}
              readOnly: true
              mountPath: {{ $volume.mountPath }}
              subPath: {{ $volume.subPath }}
{{- end }}

      volumes:
        - name: env
          configMap:
            name: {{ $.Values.service.app }}
{{- range $volume := $worker.volumeMounts }}
        - name: {{ $volume.name }}
          secret:
            secretName: {{ $.Values.onepassitem }}
            defaultMode: 432
{{- end }}

      hostAliases:
      - hostnames:
        - backoffice.templatemonster.com
        ip: 10.132.122.32

      restartPolicy: Always
      nodeSelector:
        {{ $.Values.nodeSelector.name }}: workers
      imagePullSecrets:
        - name: {{ $.Values.image.imagePullSecrets }}
      terminationGracePeriodSeconds: 30

{{- end }}

